version: 0.2

phases:
  install:
    commands:
      - echo "Installing NGINX"
      - ls -la
  build:
    commands:
      - echo "Build started on `date`"
      - ls -la

  post_build:
    commands:
      - echo "Configuring NGINX"
      - ls -la
      - pwd

artifacts:        
  files:
    - '**/*'
