version: 0.2

phases:
  install:
    commands:
      - echo installing NGINX
      
  build:
    commands:
      - echo Build started on `date`
        #- sudo cp -pvrf * /var/www/html/
      
  post_build:
    commands:
      - echo Configuring NGINX

artifacts:
   files:
     - dist/**/*

